export type Book = {
    _id: string,
    id: string,
    title: string,
    slug: string,
    subtitle: string | null,
    author: string[],
    cover_url: string,
    description: string,
    rating: number,
    ratings_count: number,
    page_count: number,
    publisher: string | null,
    categories: string[],
    reading_difficulty: "beginner" | "intermediate" | "advanced",
    read_time_minutes: number,
    learning_outcomes: string[],
    key_takeaways: string[],
    summary: string,
    isbn_10: string,
    isbn_13: string,
    published_date: Date,
    tags: string[],
    cover_image: {
      _type: "image",
      asset: {
        _type: "reference",
        _ref: string,
      },
    },
    homepage_featured: boolean,
    BS_UK_isbn_13: string,
    BS_US_isbn_13: string,
    amazon_UK_link: string,
    amazon_US_link: string,
    published_at: Date,
    _type: "summary",
  };